package db

import "github.com/kunaldevxxx/loka-backend-go/internal/models"

func getSeedCafes() []models.Cafe {
	p := func(s string) *string { return &s }
	return []models.Cafe{
		{
			CafeId:         "cafe-001",
			Name:           "Brew Haven Cafe",
			Tagline:        "Where artisanal coffee meets culinary craft",
			VenueType:      "cafe",
			Icon:           "☕",
			Location:       "Bandra West, Mumbai",
			Phone:          "+91-9820123456",
			DefaultTableId: "table-05",
			SpecialtyItemIds: []string{"item-001", "item-002", "item-003"},
			Theme: &models.CafeTheme{
				Background:        "#faf8f5",
				Foreground:        "#1c1917",
				Card:              "#ffffff",
				CardForeground:    "#1c1917",
				Primary:           "#d97706",
				PrimaryForeground: "#ffffff",
				Secondary:         "#b45309",
				SecondaryForeground: "#ffffff",
				Muted:             "#f4efe9",
				MutedForeground:   "#78716c",
				Accent:            "#f59e0b",
				AccentForeground:  "#ffffff",
				Border:            "#e7e0d8",
				FontDisplay:       p("Outfit, sans-serif"),
				FontSans:          p("Plus Jakarta Sans, sans-serif"),
			},
		},
		{
			CafeId:         "cafe-002",
			Name:           "The Daily Grind Roasters",
			Tagline:        "Fresh micro-lot roasts & sourdough bakes",
			VenueType:      "roastery",
			Icon:           "🫘",
			Location:       "Koramangala, Bangalore",
			Phone:          "+91-9845098765",
			DefaultTableId: "table-02",
			SpecialtyItemIds: []string{"item-004", "item-005"},
			Theme: &models.CafeTheme{
				Background:        "#f6fbf8",
				Foreground:        "#123026",
				Card:              "#ffffff",
				CardForeground:    "#123026",
				Primary:           "#059669",
				PrimaryForeground: "#ffffff",
				Secondary:         "#047857",
				SecondaryForeground: "#ffffff",
				Muted:             "#e8f5ed",
				MutedForeground:   "#5f7469",
				Accent:            "#10b981",
				AccentForeground:  "#ffffff",
				Border:            "#cfe5d8",
				FontDisplay:       p("Outfit, sans-serif"),
				FontSans:          p("Plus Jakarta Sans, sans-serif"),
			},
		},
		{
			CafeId:         "cafe-003",
			Name:           "Velvet Bean Lounge",
			Tagline:        "Evening espresso martinis & specialty desserts",
			VenueType:      "lounge",
			Icon:           "🍸",
			Location:       "Jubilee Hills, Hyderabad",
			Phone:          "+91-9876543210",
			DefaultTableId: "table-08",
			SpecialtyItemIds: []string{"item-006", "item-007"},
			Theme: &models.CafeTheme{
				Background:        "#1a1625",
				Foreground:        "#f5f3ff",
				Card:              "#262035",
				CardForeground:    "#f5f3ff",
				Primary:           "#a855f7",
				PrimaryForeground: "#ffffff",
				Secondary:         "#9333ea",
				SecondaryForeground: "#ffffff",
				Muted:             "#322a47",
				MutedForeground:   "#c4b5fd",
				Accent:            "#c084fc",
				AccentForeground:  "#ffffff",
				Border:            "#433765",
				FontDisplay:       p("Outfit, sans-serif"),
				FontSans:          p("Plus Jakarta Sans, sans-serif"),
			},
		},
		{
			CafeId:         "cafe-004",
			Name:           "Nordic Drift Specialty Coffee",
			Tagline:        "Minimalist scandinavian pour-overs & cinnamon buns",
			VenueType:      "specialty_bar",
			Icon:           "❄️",
			Location:       "Connaught Place, New Delhi",
			Phone:          "+91-9811223344",
			DefaultTableId: "table-03",
			SpecialtyItemIds: []string{"item-008", "item-009"},
			Theme: &models.CafeTheme{
				Background:        "#f8fafc",
				Foreground:        "#0f172a",
				Card:              "#ffffff",
				CardForeground:    "#0f172a",
				Primary:           "#0284c7",
				PrimaryForeground: "#ffffff",
				Secondary:         "#0369a1",
				SecondaryForeground: "#ffffff",
				Muted:             "#e2e8f0",
				MutedForeground:   "#64748b",
				Accent:            "#38bdf8",
				AccentForeground:  "#ffffff",
				Border:            "#cbd5e1",
				FontDisplay:       p("Outfit, sans-serif"),
				FontSans:          p("Plus Jakarta Sans, sans-serif"),
			},
		},
		{
			CafeId:         "cafe-005",
			Name:           "Artisan Bakes & Bistro",
			Tagline:        "All-day brunch, hand-laminated viennoiserie",
			VenueType:      "bakery_bistro",
			Icon:           "🥐",
			Location:       "Indiranagar, Bangalore",
			Phone:          "+91-9988776655",
			DefaultTableId: "table-04",
			SpecialtyItemIds: []string{"item-010", "item-011"},
			Theme: &models.CafeTheme{
				Background:        "#fffbeb",
				Foreground:        "#451a03",
				Card:              "#ffffff",
				CardForeground:    "#451a03",
				Primary:           "#e11d48",
				PrimaryForeground: "#ffffff",
				Secondary:         "#be123c",
				SecondaryForeground: "#ffffff",
				Muted:             "#ffe4e6",
				MutedForeground:   "#9f1239",
				Accent:            "#fb7185",
				AccentForeground:  "#ffffff",
				Border:            "#fecdd3",
				FontDisplay:       p("Outfit, sans-serif"),
				FontSans:          p("Plus Jakarta Sans, sans-serif"),
			},
		},
	}
}

func getSeedMenuItems() []models.MenuItem {
	return []models.MenuItem{
		{
			ItemId:      "item-001",
			CafeId:      "cafe-001",
			Name:        "Signature Velvet Cappuccino",
			Price:       220,
			Category:    "Beverages",
			Available:   true,
			Tags:        []string{"Chef Special", "Hot", "Signature"},
			Image:       "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&auto=format&fit=crop&q=80",
			Description: "Double shot espresso with silky microfoam and dusted Belgian cocoa.",
			Sizes: []models.MenuItemSize{
				{Label: "Regular (250ml)", Extra: 0},
				{Label: "Large (350ml)", Extra: 40},
			},
			MilkOptions: []string{"Whole Milk", "Oat Milk (+₹40)", "Almond Milk (+₹40)", "Soy Milk (+₹30)"},
			AddOns: []models.MenuItemAddOn{
				{Label: "Extra Espresso Shot", Price: 50},
				{Label: "Madagascar Vanilla Syrup", Price: 35},
				{Label: "Salted Caramel Drizzle", Price: 35},
			},
			RecommendationReason: "Our flagship roast with velvety crema, loved by coffee connoisseurs.",
		},
		{
			ItemId:      "item-002",
			CafeId:      "cafe-001",
			Name:        "Iced Spanish Latte",
			Price:       260,
			Category:    "Beverages",
			Available:   true,
			Tags:        []string{"Cold", "Bestseller"},
			Image:       "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80",
			Description: "Chilled espresso over sweet condensed milk and cold fresh milk.",
			Sizes: []models.MenuItemSize{
				{Label: "Regular (350ml)", Extra: 0},
				{Label: "Large (450ml)", Extra: 50},
			},
			MilkOptions: []string{"Whole Milk", "Oat Milk (+₹40)", "Almond Milk (+₹40)"},
			RecommendationReason: "Refreshing balanced sweetness with rich espresso punch.",
		},
		{
			ItemId:      "item-003",
			CafeId:      "cafe-001",
			Name:        "Artisan French Butter Croissant",
			Price:       180,
			Category:    "Bakery",
			Available:   true,
			Tags:        []string{"Freshly Baked", "Vegetarian"},
			Image:       "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80",
			Description: "Flaky 72-layer laminated pastry made with pure Normandy butter.",
			RecommendationReason: "Baked fresh every morning at 6 AM.",
		},
		{
			ItemId:      "item-004",
			CafeId:      "cafe-001",
			Name:        "Avocado Sourdough Tartine",
			Price:       340,
			Category:    "Food",
			Available:   true,
			Tags:        []string{"Healthy", "Vegan Option"},
			Image:       "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80",
			Description: "Hass avocado, cherry tomatoes, toasted seeds, microgreens on country sourdough.",
			RecommendationReason: "Chef Maria's favorite savory breakfast pairing.",
		},
		{
			ItemId:      "item-005",
			CafeId:      "cafe-001",
			Name:        "San Sebastian Basque Cheesecake",
			Price:       290,
			Category:    "Desserts",
			Available:   true,
			Tags:        []string{"Chef Special", "Sweet"},
			Image:       "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&auto=format&fit=crop&q=80",
			Description: "Caramelized crust with an ultra-creamy, molten cheese center.",
			RecommendationReason: "Pairs sublimely with our Dark Roast Pour-Over.",
		},
	}
}

func getSeedUsers() []models.User {
	p := func(s string) *string { return &s }
	return []models.User{
		{
			Id:         "user-001",
			Email:      "user@example.com",
			Password:   "securePassword123",
			Name:       "John Doe",
			Role:       "customer",
			CafeId:     nil,
			CreatedAt:  "2026-01-01T00:00:00Z",
			LoginCount: 5,
		},
		{
			Id:         "user-mgr-01",
			Email:      "manager@cafe.com",
			Password:   "managerPassword123",
			Name:       "Aarav Sharma",
			Role:       "manager",
			CafeId:     p("cafe-001"),
			CreatedAt:  "2026-01-01T00:00:00Z",
			LoginCount: 18,
		},
		{
			Id:         "user-chf-01",
			Email:      "chef@cafe.com",
			Password:   "chefPassword123",
			Name:       "Chef Maria Rossi",
			Role:       "chef",
			CafeId:     p("cafe-001"),
			CreatedAt:  "2026-01-01T00:00:00Z",
			LoginCount: 12,
		},
		{
			Id:         "user-sup-01",
			Email:      "support@cafe.com",
			Password:   "supportPassword123",
			Name:       "Dev Support Admin",
			Role:       "support",
			CafeId:     nil,
			CreatedAt:  "2026-01-01T00:00:00Z",
			LoginCount: 42,
		},
	}
}
